groups:
- name: Xetro
  jobs:
  - push-to-cf

jobs:
- name: push-to-cf
  serial: true
  plan:
  - in_parallel:
    - get: xetro
      trigger: true
  - task: push-to-cf
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
      inputs:
      - name: xetro
      run:
        path: xetro/ci/tasks/push-to-cf.sh
      params:
        APP_NAME:                       xetro
        CF_DOMAIN:                      {{cf_domain}}
        CF_ENDPOINT:                    {{cf_endpoint}}
        CF_ORG:                         {{cf_org}}
        CF_SPACE:                       {{cf_space}}
        CF_USERNAME:                    {{cf_username}}
        CF_PASSWORD:                    {{cf_password}}
        NODE_ENV:                       production
        DB_SERVICE_NAME:                {{db_service_name}}
        DB_USERNAME:                    {{db_username}}
        DB_PASSWORD:                    {{db_password}}
        DB_HOST:                        {{db_host}}
        DB_NAME:                        {{db_name}}
        DB_DIALECT:                     {{db_dialect}}
        SSO_MICROSOFT_CLIENT_ID:        {{sso_microsoft_client_id}}
        SSO_MICROSOFT_CLIENT_SECRET:    {{sso_microsoft_client_secret}}
        SSO_MICROSOFT_TENANT_ID:        {{sso_microsoft_tenant_id}}
        SSO_MICROSOFT_REDIRECT_URI:     {{sso_microsoft_redirect_uri}}
        SSO_DELL_CLIENT_ID:             {{sso_dell_client_id}}
        SSO_DELL_CLIENT_SECRET:         {{sso_dell_client_secret}}
        SSO_DELL_AUTH_DOMAIN:           {{sso_dell_auth_domain}}
        SSO_DELL_USERINFO:              {{sso_dell_userinfo}}

resources:
- name: xetro
  type: git
  icon: github-circle
  source:
    uri: https://github.com/kaleo211/xetro
    branch: master
    private_key: {{xetro_private_key}}
    skip_ssl_verification: true
